# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    slugger:
        class: BlogmdBundle\Utils\Slugger

    markdown:
        class: BlogmdBundle\Utils\Markdown

    app.twig.app_extension:
        public:    false
        class:     BlogmdBundle\Twig\AppExtension
        arguments: ['@markdown']
        tags:
            - { name: twig.extension }
